// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaProcessosSeletivos.Infrastructure.Data.Context;

#nullable disable

namespace SistemaProcessosSeletivos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.BancaExaminadora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EditalEtapaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EditalEtapaId");

                    b.ToTable("BancaExaminadora", "AVALIACAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.BancaMembro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BancaExaminadoraId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EhPresidente")
                        .HasColumnType("bit");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BancaExaminadoraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BancaMembro", "AVALIACAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.CampoConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("EhDadoSensivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("FormularioSecaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("TipoDado")
                        .HasColumnType("int");

                    b.Property<string>("VariavelCodigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FormularioSecaoId", "VariavelCodigo")
                        .IsUnique();

                    b.ToTable("CampoConfig", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.CampoOpcao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CampoConfigId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TextoVisivel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ValorArmazenado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampoConfigId");

                    b.ToTable("CampoOpcao", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Candidato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Pcd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PossuiCadUnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Candidato", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.DistribuicaoAvaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BancaMembroId")
                        .HasColumnType("bigint");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusAvaliacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BancaMembroId");

                    b.HasIndex("InscricaoId");

                    b.ToTable("DistribuicaoAvaliacao", "AVALIACAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Edital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("DataFimInscricao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroEdital")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("SecretariaId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusEdital")
                        .HasColumnType("int");

                    b.Property<long>("TipoProcessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SecretariaId");

                    b.HasIndex("TipoProcessoId");

                    b.ToTable("Edital", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.EditalEtapa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("EditalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EhEliminatoria")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoPonderado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoAvaliacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditalId");

                    b.ToTable("EditalEtapa", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.FormularioSecao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EditalId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EditalId");

                    b.ToTable("FormularioSecao", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Inscricao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidatoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ClassificacaoAtual")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("EditalId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("NotaFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProtocoloGerado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StatusInscricao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EditalId");

                    b.ToTable("Inscricao", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.InscricaoHistoricoStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("StatusNovoId")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoId");

                    b.HasIndex("StatusAnteriorId");

                    b.HasIndex("StatusNovoId");

                    b.ToTable("inscricao_historico_status", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.InscricaoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfiguracoesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimInscricao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroEdital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusEdital")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InscricaoStatus", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.NotaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DistribuicaoAvaliacaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("JustificativaTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaAtribuida")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("RegraPontuacaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DistribuicaoAvaliacaoId");

                    b.HasIndex("RegraPontuacaoId");

                    b.ToTable("NotaItem", "AVALIACAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Perfil", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissaoId")
                        .HasColumnType("bigint");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissao", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Permissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissao", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Recurso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<long>("EditalEtapaId")
                        .HasColumnType("bigint");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusRecurso")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecurso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditalEtapaId");

                    b.HasIndex("InscricaoId");

                    b.ToTable("Recurso", "JURIDICO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RecursoAnalise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAnalise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("DecisaoFinal")
                        .HasColumnType("bit");

                    b.Property<string>("ParecerTecnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RecursoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioAvaliadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId")
                        .IsUnique();

                    b.HasIndex("UsuarioAvaliadorId");

                    b.ToTable("RecursoAnalise", "JURIDICO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraCondicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CampoConfigId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("RegraPontuacaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValorReferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampoConfigId");

                    b.HasIndex("RegraPontuacaoId");

                    b.ToTable("RegraCondicao", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraPontuacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EditalEtapaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TipoResultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EditalEtapaId");

                    b.ToTable("RegraPontuacao", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraResultado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Pontos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PontosMaximos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("RegraPontuacaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RegraPontuacaoId")
                        .IsUnique();

                    b.ToTable("RegraResultado", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Resposta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CampoConfigId")
                        .HasColumnType("bigint");

                    b.Property<long>("InscricaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampoConfigId");

                    b.HasIndex("InscricaoId", "CampoConfigId")
                        .IsUnique();

                    b.ToTable("Resposta", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaArquivo", b =>
                {
                    b.Property<long>("RespostaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Caminho")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("RespostaId");

                    b.ToTable("RespostaArquivo", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaData", b =>
                {
                    b.Property<long>("RespostaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Valor")
                        .HasColumnType("datetime2");

                    b.HasKey("RespostaId");

                    b.ToTable("RespostaData", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaNumero", b =>
                {
                    b.Property<long>("RespostaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("RespostaId");

                    b.ToTable("RespostaNumero", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaTexto", b =>
                {
                    b.Property<long>("RespostaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RespostaId");

                    b.ToTable("RespostaTexto", "EXECUCAO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Secretaria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Secretaria", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tenant", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.TipoProcesso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequerIntegracaoSalarial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequerVagaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("TipoProcesso", "CONFIG");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuario", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.UsuarioLotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long>("SecretariaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("SecretariaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioLotacao", "ACESSO");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.BancaExaminadora", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.EditalEtapa", null)
                        .WithMany()
                        .HasForeignKey("EditalEtapaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.BancaMembro", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.BancaExaminadora", null)
                        .WithMany()
                        .HasForeignKey("BancaExaminadoraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.CampoConfig", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.FormularioSecao", null)
                        .WithMany()
                        .HasForeignKey("FormularioSecaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.CampoOpcao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.CampoConfig", null)
                        .WithMany()
                        .HasForeignKey("CampoConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.DistribuicaoAvaliacao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.BancaMembro", null)
                        .WithMany()
                        .HasForeignKey("BancaMembroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Inscricao", null)
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Edital", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Secretaria", null)
                        .WithMany()
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.TipoProcesso", null)
                        .WithMany()
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.EditalEtapa", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.FormularioSecao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Inscricoes")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Edital", null)
                        .WithMany()
                        .HasForeignKey("EditalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.InscricaoHistoricoStatus", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Inscricao", null)
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.InscricaoStatus", "StatusAnterior")
                        .WithMany()
                        .HasForeignKey("StatusAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.InscricaoStatus", "StatusNovo")
                        .WithMany()
                        .HasForeignKey("StatusNovoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StatusAnterior");

                    b.Navigation("StatusNovo");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.NotaItem", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.DistribuicaoAvaliacao", null)
                        .WithMany()
                        .HasForeignKey("DistribuicaoAvaliacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.RegraPontuacao", null)
                        .WithMany()
                        .HasForeignKey("RegraPontuacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Recurso", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.EditalEtapa", null)
                        .WithMany()
                        .HasForeignKey("EditalEtapaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Inscricao", null)
                        .WithMany()
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RecursoAnalise", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAvaliadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraCondicao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.CampoConfig", null)
                        .WithMany()
                        .HasForeignKey("CampoConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.RegraPontuacao", null)
                        .WithMany()
                        .HasForeignKey("RegraPontuacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraPontuacao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.EditalEtapa", null)
                        .WithMany()
                        .HasForeignKey("EditalEtapaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RegraResultado", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.RegraPontuacao", null)
                        .WithMany()
                        .HasForeignKey("RegraPontuacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Resposta", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.CampoConfig", null)
                        .WithMany()
                        .HasForeignKey("CampoConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Inscricao", "Inscricao")
                        .WithMany("Respostas")
                        .HasForeignKey("InscricaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inscricao");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaArquivo", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Resposta", "Resposta")
                        .WithOne()
                        .HasForeignKey("SistemaProcessosSeletivos.Domain.Entities.RespostaArquivo", "RespostaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaData", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Resposta", "Resposta")
                        .WithOne()
                        .HasForeignKey("SistemaProcessosSeletivos.Domain.Entities.RespostaData", "RespostaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaNumero", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Resposta", "Resposta")
                        .WithOne()
                        .HasForeignKey("SistemaProcessosSeletivos.Domain.Entities.RespostaNumero", "RespostaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.RespostaTexto", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Resposta", "Resposta")
                        .WithOne()
                        .HasForeignKey("SistemaProcessosSeletivos.Domain.Entities.RespostaTexto", "RespostaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Secretaria", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.UsuarioLotacao", b =>
                {
                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Secretaria", null)
                        .WithMany()
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaProcessosSeletivos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("SistemaProcessosSeletivos.Domain.Entities.Inscricao", b =>
                {
                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
